-- +goose Up
-- +goose StatementBegin
-- MySQL Script generated by MySQL Workbench
-- Thu Jan  6 22:35:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema covid19hk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema covid19hk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `covid19hk` DEFAULT CHARACTER SET utf8mb4 ;
USE `covid19hk` ;

-- -----------------------------------------------------
-- Table `covid19hk`.`case_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid19hk`.`case_history` (
  `enabled` VARCHAR(1) NOT NULL DEFAULT [Internal] Should the record be published?,
  `case_no` INT NOT NULL DEFAULT Case number of confirmed patient,
  `onset_date` DATE NULL DEFAULT The date of patient started having symptoms,
  `confirmation_date` DATE NOT NULL DEFAULT The date of patient confirmed infected by the authorities,
  `gender` VARCHAR(1) NOT NULL DEFAULT 'The gender of patient',
  `age` INT(3) NOT NULL DEFAULT The age of patient,
  `hospital_code` VARCHAR(255) NOT NULL DEFAULT ,
  `status_code` VARCHAR(255) NOT NULL DEFAULT 'Shortcode for the status of the patient',
  `type_code` VARCHAR(255) NOT NULL DEFAULT 'Shortcode for the type of reported case',
  `residency_code` VARCHAR(1) NOT NULL DEFAULT 'Is the patient a Hong Kong resident?',
  `citizenship_code` VARCHAR(255) NOT NULL DEFAULT 'Shortcode for the country the patient usually stays at',
  `classification_code` VARCHAR(255) NOT NULL DEFAULT 'Shortcode for the classification of reported case, assigned by the CHP',
  `details_zh` LONGTEXT NOT NULL DEFAULT 'Description of the reported case in Traditional Chinese (Hong Kong)',
  `details_en` LONGTEXT NOT NULL DEFAULT 'Description of the reported case in English',
  `t9n_update_required` VARCHAR(1) NOT NULL DEFAULT '[Internal] Is the \'details\' columns need a translation update?',
  `source_url_1` VARCHAR(2048) NULL DEFAULT 'URL link to the 1st source describing the reported case',
  `source_url_2` VARCHAR(2048) NULL DEFAULT 'URL link to the 2nd source describing the reported case',
  `source_url_3` VARCHAR(2048) NULL DEFAULT 'URL link to the 3rd source describing the reported case',
  `source_url_4` VARCHAR(2048) NULL DEFAULT 'URL link to the 4th source describing the reported case',
  `source_url_5` VARCHAR(2048) NULL DEFAULT 'URL link to the 5th source describing the reported case',
  PRIMARY KEY (`case_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid19hk`.`location_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid19hk`.`location_history` (
  `enabled` VARCHAR(1) NOT NULL DEFAULT [Internal] Should the record be published?,
  `case_no` INT NOT NULL DEFAULT Case number of confirmed patient,
  `start_date` DATE NOT NULL,
  `start_time_period` VARCHAR(255) NULL,
  `end_date` DATE NOT NULL,
  `end_time_period` VARCHAR(255) NULL,
  `type_code` VARCHAR(255) NOT NULL,
  `loc_district_code` VARCHAR(255) NOT NULL,
  `loc_poi_code` VARCHAR(255) NOT NULL,
  `loc_name_zh` VARCHAR(2048) NOT NULL,
  `loc_name_en` VARCHAR(2048) NOT NULL,
  `action_code` VARCHAR(1) NOT NULL,
  `remarks_zh` VARCHAR(255) NOT NULL,
  `remarks_en` VARCHAR(255) NOT NULL,
  `coordinates` POINT NOT NULL,
  `source_url_1` VARCHAR(2048) NOT NULL,
  `source_url_2` VARCHAR(2048) NOT NULL,
  `source_file_date` VARCHAR(2048) NOT NULL,
  `source_file_type` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`case_no`))
ENGINE = InnoDB;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
